"""add isbn to livros

Revision ID: 6d65ad6de28c
Revises: 8a213f19566c
Create Date: 2026-08-21 12:29:31.251528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d65ad6de28c'
down_revision: Union[str, Sequence[str], None] = '8a213f19566c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('isbn', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livros', 'isbn')
    # ### end Alembic commands ###
