"""create livros table

Revision ID: 8a213f19566c
Revises: 
Create Date: 2026-08-21 11:20:23.632943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a213f19566c' # O Alembic utiliza esse ID para controlar qual versão do banco está instalada.

# Esta é a primeira migration do projeto, portanto ela não depende de nenhuma migration anterior.
down_revision: Union[str, Sequence[str], None] = None

# Utilizado quando existem múltiplas linhas de migration.
branch_labels: Union[str, Sequence[str], None] = None

# Permite declarar dependências entre migrations.
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    """
    Leva o banco para esta versão.

    Neste caso, a primeira migration cria a tabela de livros.
    (ESSE COMPORTAMENTO É APENAS PARA O PROJETO ATUAL, POIS AS TABELAS PODEM NÃO EXISTIR)
    """

    op.create_table(
        "livros",

        # Equivalente ao:
        # id: Mapped[int] = mapped_column(
        #     primary_key=True,
        #     autoincrement=True
        # )
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False
        ),

        # Equivalente ao:
        # titulo: Mapped[str] = mapped_column(
        #     String(200),
        #     nullable=False
        # )
        sa.Column(
            "titulo",
            sa.String(length=200),
            nullable=False
        ),

        # Equivalente ao:
        # autor: Mapped[str] = mapped_column(
        #     String(200),
        #     nullable=False
        # )
        sa.Column(
            "autor",
            sa.String(length=200),
            nullable=False
        ),

        # Equivalente ao:
        # ano: Mapped[int] = mapped_column(
        #     nullable=False
        # )
        sa.Column(
            "ano",
            sa.Integer(),
            nullable=False
        ),

        # Equivalente ao:
        # primary_key=True
        sa.PrimaryKeyConstraint("id")
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    """
    Retorna o banco para o estado anterior a esta migration.

    Como esta é a primeira migration,
    o estado anterior não possui a tabela livros.
    """

    op.drop_table("livros")
